# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sfu.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'sfu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsfu.proto\x12\x03sfu\"*\n\x14\x43reateSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"+\n\x15\x43reateSessionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\"/\n\x0cOfferRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0b\n\x03sdp\x18\x02 \x01(\t\"\x1d\n\x0e\x41nswerResponse\x12\x0b\n\x03sdp\x18\x01 \x01(\t\"A\n\x13IceCandidateRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63\x61ndidate_json\x18\x02 \x01(\t\"G\n\nAudioChunk\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08pcm_data\x18\x02 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\"\x1f\n\tSessionID\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xdd\x02\n\nSFUService\x12\x46\n\rCreateSession\x12\x19.sfu.CreateSessionRequest\x1a\x1a.sfu.CreateSessionResponse\x12\x36\n\x0cProcessOffer\x12\x11.sfu.OfferRequest\x1a\x13.sfu.AnswerResponse\x12\x37\n\x0f\x41\x64\x64IceCandidate\x12\x18.sfu.IceCandidateRequest\x1a\n.sfu.Empty\x12\x32\n\x11StreamAudioToPion\x12\x0f.sfu.AudioChunk\x1a\n.sfu.Empty(\x01\x12\x38\n\x13StreamAudioFromPion\x12\x0e.sfu.SessionID\x1a\x0f.sfu.AudioChunk0\x01\x12(\n\nEndSession\x12\x0e.sfu.SessionID\x1a\n.sfu.EmptyB\x08Z\x06./;sfub\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sfu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006./;sfu'
  _globals['_CREATESESSIONREQUEST']._serialized_start=18
  _globals['_CREATESESSIONREQUEST']._serialized_end=60
  _globals['_CREATESESSIONRESPONSE']._serialized_start=62
  _globals['_CREATESESSIONRESPONSE']._serialized_end=105
  _globals['_OFFERREQUEST']._serialized_start=107
  _globals['_OFFERREQUEST']._serialized_end=154
  _globals['_ANSWERRESPONSE']._serialized_start=156
  _globals['_ANSWERRESPONSE']._serialized_end=185
  _globals['_ICECANDIDATEREQUEST']._serialized_start=187
  _globals['_ICECANDIDATEREQUEST']._serialized_end=252
  _globals['_AUDIOCHUNK']._serialized_start=254
  _globals['_AUDIOCHUNK']._serialized_end=325
  _globals['_SESSIONID']._serialized_start=327
  _globals['_SESSIONID']._serialized_end=358
  _globals['_EMPTY']._serialized_start=360
  _globals['_EMPTY']._serialized_end=367
  _globals['_SFUSERVICE']._serialized_start=370
  _globals['_SFUSERVICE']._serialized_end=719
# @@protoc_insertion_point(module_scope)
