# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sfu_pb2 as sfu__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sfu_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SFUServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/sfu.SFUService/CreateSession',
                request_serializer=sfu__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=sfu__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.ProcessOffer = channel.unary_unary(
                '/sfu.SFUService/ProcessOffer',
                request_serializer=sfu__pb2.OfferRequest.SerializeToString,
                response_deserializer=sfu__pb2.AnswerResponse.FromString,
                _registered_method=True)
        self.AddIceCandidate = channel.unary_unary(
                '/sfu.SFUService/AddIceCandidate',
                request_serializer=sfu__pb2.IceCandidateRequest.SerializeToString,
                response_deserializer=sfu__pb2.Empty.FromString,
                _registered_method=True)
        self.StreamAudioToPion = channel.stream_unary(
                '/sfu.SFUService/StreamAudioToPion',
                request_serializer=sfu__pb2.AudioChunk.SerializeToString,
                response_deserializer=sfu__pb2.Empty.FromString,
                _registered_method=True)
        self.StreamAudioFromPion = channel.unary_stream(
                '/sfu.SFUService/StreamAudioFromPion',
                request_serializer=sfu__pb2.SessionID.SerializeToString,
                response_deserializer=sfu__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/sfu.SFUService/EndSession',
                request_serializer=sfu__pb2.SessionID.SerializeToString,
                response_deserializer=sfu__pb2.Empty.FromString,
                _registered_method=True)


class SFUServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessOffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddIceCandidate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAudioToPion(self, request_iterator, context):
        """FastAPI → Pion (TTS audio)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAudioFromPion(self, request, context):
        """Pion → FastAPI (user audio)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SFUServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=sfu__pb2.CreateSessionRequest.FromString,
                    response_serializer=sfu__pb2.CreateSessionResponse.SerializeToString,
            ),
            'ProcessOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessOffer,
                    request_deserializer=sfu__pb2.OfferRequest.FromString,
                    response_serializer=sfu__pb2.AnswerResponse.SerializeToString,
            ),
            'AddIceCandidate': grpc.unary_unary_rpc_method_handler(
                    servicer.AddIceCandidate,
                    request_deserializer=sfu__pb2.IceCandidateRequest.FromString,
                    response_serializer=sfu__pb2.Empty.SerializeToString,
            ),
            'StreamAudioToPion': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamAudioToPion,
                    request_deserializer=sfu__pb2.AudioChunk.FromString,
                    response_serializer=sfu__pb2.Empty.SerializeToString,
            ),
            'StreamAudioFromPion': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAudioFromPion,
                    request_deserializer=sfu__pb2.SessionID.FromString,
                    response_serializer=sfu__pb2.AudioChunk.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=sfu__pb2.SessionID.FromString,
                    response_serializer=sfu__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sfu.SFUService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sfu.SFUService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SFUService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sfu.SFUService/CreateSession',
            sfu__pb2.CreateSessionRequest.SerializeToString,
            sfu__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sfu.SFUService/ProcessOffer',
            sfu__pb2.OfferRequest.SerializeToString,
            sfu__pb2.AnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddIceCandidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sfu.SFUService/AddIceCandidate',
            sfu__pb2.IceCandidateRequest.SerializeToString,
            sfu__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAudioToPion(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/sfu.SFUService/StreamAudioToPion',
            sfu__pb2.AudioChunk.SerializeToString,
            sfu__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAudioFromPion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sfu.SFUService/StreamAudioFromPion',
            sfu__pb2.SessionID.SerializeToString,
            sfu__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sfu.SFUService/EndSession',
            sfu__pb2.SessionID.SerializeToString,
            sfu__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
